### ISSUE TITLE
obsSceneChanged not triggered when hotkey

### ISSUE THREAD

**Issue by padinko** [kc5nra/obs-browser#59] opened 2017-01-17 21:08 UTC
Hello,
when I change scene with global hotkey, the event 'obsSceneChanged' is not triggered. when i press hotkey second time then its fire to last scene changed

**Comment by OsirisNL** [comment] 2017-01-17 21:12
This works perfectly fine here

**Comment by padinko** [comment] 2017-01-17 21:25
i test it more and it trigger the event, but with scene name before the change, not scene changed to

**Comment by OsirisNL** [comment] 2017-01-18 21:16
Yeah looks like i can reproduce it now, seems a bug in obs studio itself. I've reported it.

**Comment by padinko** [comment] 2017-03-11 17:26
on 18.0.1 scene chenge is triggered after the transition effect and works good with global hotkey

**Comment by OsirisNL** [comment] 2017-03-11 17:30
Fixed in OBS Studio 18.0.0

**Closed by OsirisNL** 2017-03-11 17:30 UTC
